-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('LandlordsProto_pb')


local CS_PLAYERLOGIN = protobuf.Descriptor();
local CS_PLAYERLOGIN_ACCOUNT_FIELD = protobuf.FieldDescriptor();
local CS_PLAYERLOGIN_PWD_FIELD = protobuf.FieldDescriptor();
local SC_PLAYERLOGIN = protobuf.Descriptor();
local SC_PLAYERLOGIN_RESULT_FIELD = protobuf.FieldDescriptor();
local CS_PLAYERREGISTER = protobuf.Descriptor();
local CS_PLAYERREGISTER_ACCOUNT_FIELD = protobuf.FieldDescriptor();
local CS_PLAYERREGISTER_PWD_FIELD = protobuf.FieldDescriptor();
local SC_PLAYERREGISTER = protobuf.Descriptor();
local SC_PLAYERREGISTER_RESULT_FIELD = protobuf.FieldDescriptor();
local CS_HEARTBEAT = protobuf.Descriptor();
local SC_HEARTBEAT = protobuf.Descriptor();
local SC_HEARTBEAT_SERVERTIME_FIELD = protobuf.FieldDescriptor();

CS_PLAYERLOGIN_ACCOUNT_FIELD.name = "account"
CS_PLAYERLOGIN_ACCOUNT_FIELD.full_name = ".msg.CS_PlayerLogin.account"
CS_PLAYERLOGIN_ACCOUNT_FIELD.number = 1
CS_PLAYERLOGIN_ACCOUNT_FIELD.index = 0
CS_PLAYERLOGIN_ACCOUNT_FIELD.label = 1
CS_PLAYERLOGIN_ACCOUNT_FIELD.has_default_value = false
CS_PLAYERLOGIN_ACCOUNT_FIELD.default_value = ""
CS_PLAYERLOGIN_ACCOUNT_FIELD.type = 9
CS_PLAYERLOGIN_ACCOUNT_FIELD.cpp_type = 9

CS_PLAYERLOGIN_PWD_FIELD.name = "pwd"
CS_PLAYERLOGIN_PWD_FIELD.full_name = ".msg.CS_PlayerLogin.pwd"
CS_PLAYERLOGIN_PWD_FIELD.number = 2
CS_PLAYERLOGIN_PWD_FIELD.index = 1
CS_PLAYERLOGIN_PWD_FIELD.label = 1
CS_PLAYERLOGIN_PWD_FIELD.has_default_value = false
CS_PLAYERLOGIN_PWD_FIELD.default_value = ""
CS_PLAYERLOGIN_PWD_FIELD.type = 9
CS_PLAYERLOGIN_PWD_FIELD.cpp_type = 9

CS_PLAYERLOGIN.name = "CS_PlayerLogin"
CS_PLAYERLOGIN.full_name = ".msg.CS_PlayerLogin"
CS_PLAYERLOGIN.nested_types = {}
CS_PLAYERLOGIN.enum_types = {}
CS_PLAYERLOGIN.fields = {CS_PLAYERLOGIN_ACCOUNT_FIELD, CS_PLAYERLOGIN_PWD_FIELD}
CS_PLAYERLOGIN.is_extendable = false
CS_PLAYERLOGIN.extensions = {}
SC_PLAYERLOGIN_RESULT_FIELD.name = "result"
SC_PLAYERLOGIN_RESULT_FIELD.full_name = ".msg.SC_PlayerLogin.result"
SC_PLAYERLOGIN_RESULT_FIELD.number = 1
SC_PLAYERLOGIN_RESULT_FIELD.index = 0
SC_PLAYERLOGIN_RESULT_FIELD.label = 1
SC_PLAYERLOGIN_RESULT_FIELD.has_default_value = false
SC_PLAYERLOGIN_RESULT_FIELD.default_value = 0
SC_PLAYERLOGIN_RESULT_FIELD.type = 17
SC_PLAYERLOGIN_RESULT_FIELD.cpp_type = 1

SC_PLAYERLOGIN.name = "SC_PlayerLogin"
SC_PLAYERLOGIN.full_name = ".msg.SC_PlayerLogin"
SC_PLAYERLOGIN.nested_types = {}
SC_PLAYERLOGIN.enum_types = {}
SC_PLAYERLOGIN.fields = {SC_PLAYERLOGIN_RESULT_FIELD}
SC_PLAYERLOGIN.is_extendable = false
SC_PLAYERLOGIN.extensions = {}
CS_PLAYERREGISTER_ACCOUNT_FIELD.name = "account"
CS_PLAYERREGISTER_ACCOUNT_FIELD.full_name = ".msg.CS_PlayerRegister.account"
CS_PLAYERREGISTER_ACCOUNT_FIELD.number = 1
CS_PLAYERREGISTER_ACCOUNT_FIELD.index = 0
CS_PLAYERREGISTER_ACCOUNT_FIELD.label = 1
CS_PLAYERREGISTER_ACCOUNT_FIELD.has_default_value = false
CS_PLAYERREGISTER_ACCOUNT_FIELD.default_value = ""
CS_PLAYERREGISTER_ACCOUNT_FIELD.type = 9
CS_PLAYERREGISTER_ACCOUNT_FIELD.cpp_type = 9

CS_PLAYERREGISTER_PWD_FIELD.name = "pwd"
CS_PLAYERREGISTER_PWD_FIELD.full_name = ".msg.CS_PlayerRegister.pwd"
CS_PLAYERREGISTER_PWD_FIELD.number = 2
CS_PLAYERREGISTER_PWD_FIELD.index = 1
CS_PLAYERREGISTER_PWD_FIELD.label = 1
CS_PLAYERREGISTER_PWD_FIELD.has_default_value = false
CS_PLAYERREGISTER_PWD_FIELD.default_value = ""
CS_PLAYERREGISTER_PWD_FIELD.type = 9
CS_PLAYERREGISTER_PWD_FIELD.cpp_type = 9

CS_PLAYERREGISTER.name = "CS_PlayerRegister"
CS_PLAYERREGISTER.full_name = ".msg.CS_PlayerRegister"
CS_PLAYERREGISTER.nested_types = {}
CS_PLAYERREGISTER.enum_types = {}
CS_PLAYERREGISTER.fields = {CS_PLAYERREGISTER_ACCOUNT_FIELD, CS_PLAYERREGISTER_PWD_FIELD}
CS_PLAYERREGISTER.is_extendable = false
CS_PLAYERREGISTER.extensions = {}
SC_PLAYERREGISTER_RESULT_FIELD.name = "result"
SC_PLAYERREGISTER_RESULT_FIELD.full_name = ".msg.SC_PlayerRegister.result"
SC_PLAYERREGISTER_RESULT_FIELD.number = 1
SC_PLAYERREGISTER_RESULT_FIELD.index = 0
SC_PLAYERREGISTER_RESULT_FIELD.label = 1
SC_PLAYERREGISTER_RESULT_FIELD.has_default_value = false
SC_PLAYERREGISTER_RESULT_FIELD.default_value = 0
SC_PLAYERREGISTER_RESULT_FIELD.type = 17
SC_PLAYERREGISTER_RESULT_FIELD.cpp_type = 1

SC_PLAYERREGISTER.name = "SC_PlayerRegister"
SC_PLAYERREGISTER.full_name = ".msg.SC_PlayerRegister"
SC_PLAYERREGISTER.nested_types = {}
SC_PLAYERREGISTER.enum_types = {}
SC_PLAYERREGISTER.fields = {SC_PLAYERREGISTER_RESULT_FIELD}
SC_PLAYERREGISTER.is_extendable = false
SC_PLAYERREGISTER.extensions = {}
CS_HEARTBEAT.name = "CS_Heartbeat"
CS_HEARTBEAT.full_name = ".msg.CS_Heartbeat"
CS_HEARTBEAT.nested_types = {}
CS_HEARTBEAT.enum_types = {}
CS_HEARTBEAT.fields = {}
CS_HEARTBEAT.is_extendable = false
CS_HEARTBEAT.extensions = {}
SC_HEARTBEAT_SERVERTIME_FIELD.name = "serverTime"
SC_HEARTBEAT_SERVERTIME_FIELD.full_name = ".msg.SC_Heartbeat.serverTime"
SC_HEARTBEAT_SERVERTIME_FIELD.number = 1
SC_HEARTBEAT_SERVERTIME_FIELD.index = 0
SC_HEARTBEAT_SERVERTIME_FIELD.label = 1
SC_HEARTBEAT_SERVERTIME_FIELD.has_default_value = false
SC_HEARTBEAT_SERVERTIME_FIELD.default_value = 0
SC_HEARTBEAT_SERVERTIME_FIELD.type = 18
SC_HEARTBEAT_SERVERTIME_FIELD.cpp_type = 2

SC_HEARTBEAT.name = "SC_Heartbeat"
SC_HEARTBEAT.full_name = ".msg.SC_Heartbeat"
SC_HEARTBEAT.nested_types = {}
SC_HEARTBEAT.enum_types = {}
SC_HEARTBEAT.fields = {SC_HEARTBEAT_SERVERTIME_FIELD}
SC_HEARTBEAT.is_extendable = false
SC_HEARTBEAT.extensions = {}

CS_Heartbeat = protobuf.Message(CS_HEARTBEAT)
CS_PlayerLogin = protobuf.Message(CS_PLAYERLOGIN)
CS_PlayerRegister = protobuf.Message(CS_PLAYERREGISTER)
SC_Heartbeat = protobuf.Message(SC_HEARTBEAT)
SC_PlayerLogin = protobuf.Message(SC_PLAYERLOGIN)
SC_PlayerRegister = protobuf.Message(SC_PLAYERREGISTER)

